name: Do the thing

on:
  push:
    branches: [ master ]

jobs:
  do_the_thing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: pypoetry-virtualenv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry env info
        poetry install
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Do the thing
      run: |
        poetry run python sync.py
      env:
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
