name: Do the thing

on:
  push:
    branches: [ master ]

jobs:
  do_the_thing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pypoetry/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Do the thing
      run: |
        poetry run python sync.py
      env:
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
